-- V11 : mentions dans les commentaires (§6.4, ADR-24 - docs/DECISIONS.md).
--
-- La table avait existé en V2 puis été retirée par V3 ("relève du §6.4 mais ne fait pas
-- partie du lot en cours"). Elle revient avec le cas d'usage qui l'écrit, cette fois : une
-- ligne par personne effectivement mentionnée ET habilitée à lire la demande (ADR-24 - une
-- mention vers quelqu'un hors périmètre n'est jamais enregistrée, RG-06).
--
-- Aucun id figé ici : cette migration s'applique sur des bases déjà utilisées
-- (cf. l'incident V9 documenté dans CLAUDE.md), donc l'identité génère les clés.

create table comment_mentions (
    id                  bigint generated by default as identity primary key,
    comment_id          bigint not null references comments (id),
    mentioned_user_id   bigint not null references users (id),
    created_at          timestamptz not null default now(),
    constraint uq_comment_mentions unique (comment_id, mentioned_user_id)
);

create index idx_comment_mentions_user on comment_mentions (mentioned_user_id);

-- §6.8/§6.10 - MENTION est un NotificationType comme les autres : MailService résout son
-- gabarit par le code, donc sans cette ligne l'e-mail se contenterait d'un avertissement
-- journalisé (comportement dégradé volontaire de MailService, cf. V6).
insert into email_templates (code, subject, body_html) values
    ('MENTION', 'Vous avez été mentionné sur la demande {{reference}}',
     '<p>Bonjour,</p><p><strong>{{author}}</strong> vous a mentionné dans un commentaire sur la demande <strong>{{reference}}</strong> ({{title}}).</p>');
