-- V2 : schéma de domaine initial.
--
-- Matérialise les entités JPA de domain/entity. Ancrage : cahier des charges §10 (modèle
-- de données), §10.1 (contraintes), §7 (RG-01 à RG-12).
--
-- Ordre des tables : dépendances de clé étrangère résolues par création séquentielle ;
-- la seule dépendance circulaire (departments.lead_id <-> users.department_id) est cassée
-- par un ALTER TABLE différé après la création de users.

-- ---------------------------------------------------------------------------------------
-- Organisation & identité
-- ---------------------------------------------------------------------------------------

create table departments (
    id                  bigint generated by default as identity primary key,
    name                varchar(255) not null,
    parent_department_id bigint references departments (id),
    lead_id             bigint,
    active              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

create table users (
    id              bigint generated by default as identity primary key,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    email           varchar(255) not null,
    password_hash   varchar(255) not null,
    department_id   bigint references departments (id),
    manager_id      bigint references users (id),
    active          boolean not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint uq_users_email unique (email)
);

alter table departments
    add constraint fk_departments_lead foreign key (lead_id) references users (id);

create table teams (
    id              bigint generated by default as identity primary key,
    name            varchar(255) not null,
    department_id   bigint not null references departments (id),
    lead_id         bigint references users (id),
    active          boolean not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- RG-11 : les changements de rôle et d'affectation passent par le journal d'audit ; cette
-- table ne fait qu'attribuer le rôle, elle ne remplace pas audit_log.
create table user_role_assignments (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id),
    role        varchar(32) not null,
    scope_type  varchar(16) not null,
    scope_id    bigint,
    created_at  timestamptz not null default now(),
    constraint uq_user_role_scope unique (user_id, role, scope_type, scope_id)
);

-- ADR-01 (docs/DECISIONS.md) : JWT stateless + refresh token révocable.
create table refresh_tokens (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id),
    token_hash  varchar(255) not null,
    issued_at   timestamptz not null,
    expires_at  timestamptz not null,
    revoked_at  timestamptz,
    constraint uq_refresh_tokens_hash unique (token_hash)
);

-- ---------------------------------------------------------------------------------------
-- Catalogue & formulaires configurables
-- ---------------------------------------------------------------------------------------

create table service_catalog (
    id              bigint generated by default as identity primary key,
    name            varchar(255) not null,
    description     text,
    category        varchar(100),
    department_id   bigint not null references departments (id),
    active          boolean not null default true,
    display_order   integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table request_types (
    id                          bigint generated by default as identity primary key,
    service_catalog_id         bigint not null references service_catalog (id),
    name                       varchar(255) not null,
    description                text,
    target_delay_description   varchar(255),
    required_documents         text,
    contact_info               text,
    active                     boolean not null default true,
    display_order              integer not null default 0,
    created_at                 timestamptz not null default now(),
    updated_at                 timestamptz not null default now()
);

-- §10.1 : versionnement des définitions de formulaire, immuables une fois publiées.
create table form_definitions (
    id                  bigint generated by default as identity primary key,
    request_type_id     bigint not null references request_types (id),
    version             integer not null,
    status              varchar(16) not null default 'DRAFT',
    published_at        timestamptz,
    created_at          timestamptz not null default now(),
    constraint uq_form_definitions_version unique (request_type_id, version)
);

create table form_fields (
    id                          bigint generated by default as identity primary key,
    form_definition_id          bigint not null references form_definitions (id),
    code                        varchar(100) not null,
    label                       varchar(255) not null,
    field_type                  varchar(16) not null,
    required                    boolean not null default false,
    display_order               integer not null default 0,
    help_text                   text,
    visible_when_field_code     varchar(100),
    visible_when_value          varchar(255),
    constraint uq_form_fields_code unique (form_definition_id, code)
);

create table field_options (
    id              bigint generated by default as identity primary key,
    form_field_id   bigint not null references form_fields (id),
    value           varchar(255) not null,
    label           varchar(255) not null,
    display_order   integer not null default 0
);

-- ---------------------------------------------------------------------------------------
-- Workflow (§6.5) — versionné, figé à la soumission (RG-03)
-- ---------------------------------------------------------------------------------------

create table workflow_definitions (
    id                  bigint generated by default as identity primary key,
    request_type_id     bigint not null references request_types (id),
    version             integer not null,
    status              varchar(16) not null default 'DRAFT',
    published_at        timestamptz,
    created_at          timestamptz not null default now(),
    constraint uq_workflow_definitions_version unique (request_type_id, version)
);

create table steps (
    id                      bigint generated by default as identity primary key,
    workflow_definition_id  bigint not null references workflow_definitions (id),
    code                    varchar(100) not null,
    name                    varchar(255) not null,
    display_order           integer not null default 0,
    responsible_role        varchar(32),
    responsible_team_id     bigint references teams (id),
    constraint uq_steps_code unique (workflow_definition_id, code)
);

create table transitions (
    id                          bigint generated by default as identity primary key,
    from_step_id                bigint not null references steps (id),
    action                      varchar(16) not null,
    to_step_id                  bigint references steps (id),
    condition_priority          varchar(16),
    condition_department_id     bigint references departments (id),
    condition_field_code        varchar(100),
    condition_field_value       varchar(255)
);

-- ---------------------------------------------------------------------------------------
-- Demandes (§6.4)
-- ---------------------------------------------------------------------------------------

-- RG-01 : référence unique et non réutilisable, jamais count(*) + 1. La séquence alimente
-- la partie numérique de la référence lisible (ex. DEM-2026-000123), composée en service.
create sequence request_reference_seq start with 1 increment by 1;

create table requests (
    id                              bigint generated by default as identity primary key,
    reference                       varchar(32) not null,
    request_type_id                 bigint not null references request_types (id),
    workflow_definition_id          bigint references workflow_definitions (id),
    current_step_id                 bigint references steps (id),
    status                          varchar(16) not null default 'DRAFT',
    priority                        varchar(16),
    requester_id                    bigint not null references users (id),
    title                           varchar(255) not null,
    description                     text,
    submitted_at                    timestamptz,
    closed_at                       timestamptz,
    closure_reason                  text,
    closure_solution                text,
    satisfaction_rating             integer,
    reopen_deadline                 timestamptz,
    sla_due_at_first_response       timestamptz,
    sla_due_at_resolution           timestamptz,
    sla_status                      varchar(16),
    sla_suspended_since             timestamptz,
    created_at                      timestamptz not null default now(),
    updated_at                      timestamptz not null default now(),
    constraint uq_requests_reference unique (reference)
);

create table request_field_values (
    id              bigint generated by default as identity primary key,
    request_id      bigint not null references requests (id),
    form_field_id   bigint not null references form_fields (id),
    value           text,
    updated_at      timestamptz not null default now(),
    constraint uq_request_field_values unique (request_id, form_field_id)
);

create table comments (
    id          bigint generated by default as identity primary key,
    request_id  bigint not null references requests (id),
    author_id   bigint not null references users (id),
    body        text not null,
    created_at  timestamptz not null default now()
);

create table comment_mentions (
    id                  bigint generated by default as identity primary key,
    comment_id          bigint not null references comments (id),
    mentioned_user_id   bigint not null references users (id),
    constraint uq_comment_mentions unique (comment_id, mentioned_user_id)
);

-- RG-09 : extension, taille et type MIME contrôlés côté serveur avant l'insertion de la
-- ligne. stored_filename est un nom généré non devinable ; storage_path reste hors
-- répertoire public.
create table attachments (
    id                  bigint generated by default as identity primary key,
    request_id          bigint not null references requests (id),
    uploaded_by_id       bigint not null references users (id),
    original_filename   varchar(255) not null,
    stored_filename     varchar(255) not null,
    content_type        varchar(255) not null,
    extension           varchar(20) not null,
    size_bytes          bigint not null,
    storage_path        varchar(500) not null,
    uploaded_at         timestamptz not null default now(),
    constraint uq_attachments_stored_filename unique (stored_filename)
);

-- RG-04, RG-05, §3.4 : une ligne par transition exécutée, 100 % des changements d'état
-- tracés. comment est obligatoire pour l'action REJECT — contrainte applicative
-- (domain/rule), pas un NOT NULL général puisqu'elle ne s'applique qu'à cette action.
create table request_history (
    id              bigint generated by default as identity primary key,
    request_id      bigint not null references requests (id),
    from_step_id    bigint references steps (id),
    action          varchar(16) not null,
    to_step_id      bigint references steps (id),
    actor_id        bigint not null references users (id),
    comment         text,
    occurred_at     timestamptz not null default now()
);

create table task_assignments (
    id                  bigint generated by default as identity primary key,
    request_id          bigint not null references requests (id),
    assigned_user_id    bigint references users (id),
    assigned_team_id    bigint references teams (id),
    assigned_by_id      bigint not null references users (id),
    active              boolean not null default true,
    assigned_at         timestamptz not null default now()
);

-- Une seule affectation active à la fois par demande (file "Mes tâches", §6.6).
create unique index uq_task_assignments_active_per_request
    on task_assignments (request_id)
    where active;

-- ---------------------------------------------------------------------------------------
-- SLA (§6.7, RG-07 — modèle événementiel)
-- ---------------------------------------------------------------------------------------

create table sla (
    id                          bigint generated by default as identity primary key,
    request_type_id             bigint not null references request_types (id),
    priority                    varchar(16) not null,
    first_response_minutes      integer not null,
    resolution_minutes          integer not null,
    use_business_calendar       boolean not null default true,
    constraint uq_sla_type_priority unique (request_type_id, priority)
);

create table sla_events (
    id          bigint generated by default as identity primary key,
    request_id  bigint not null references requests (id),
    event_type  varchar(32) not null,
    occurred_at timestamptz not null default now(),
    note        varchar(500)
);

-- ---------------------------------------------------------------------------------------
-- Notifications (§6.8)
-- ---------------------------------------------------------------------------------------

create table notifications (
    id              bigint generated by default as identity primary key,
    recipient_id    bigint not null references users (id),
    type            varchar(16) not null,
    request_id      bigint references requests (id),
    title           varchar(255) not null,
    body            text,
    read_at         timestamptz,
    created_at      timestamptz not null default now()
);

create table notification_preferences (
    id                  bigint generated by default as identity primary key,
    user_id             bigint not null references users (id),
    notification_type   varchar(16) not null,
    email_enabled       boolean not null default true,
    constraint uq_notification_preferences unique (user_id, notification_type)
);

create table email_templates (
    id          bigint generated by default as identity primary key,
    code        varchar(100) not null,
    subject     varchar(255) not null,
    body_html   text not null,
    updated_at  timestamptz not null default now(),
    constraint uq_email_templates_code unique (code)
);

-- ---------------------------------------------------------------------------------------
-- Intelligence artificielle (§12 — aide validée par un humain, RG-10)
-- ---------------------------------------------------------------------------------------

create table knowledge_documents (
    id                  bigint generated by default as identity primary key,
    service_catalog_id  bigint references service_catalog (id),
    title               varchar(255) not null,
    content             text,
    version             integer not null default 1,
    active              boolean not null default true,
    indexed_at          timestamptz,
    created_at          timestamptz not null default now()
);

create table ai_analyses (
    id                  bigint generated by default as identity primary key,
    request_id          bigint not null references requests (id),
    analysis_type       varchar(32) not null,
    raw_result          text,
    confidence_score    double precision,
    suggested_value     text,
    accepted_value      text,
    validated_by_id     bigint references users (id),
    validated_at        timestamptz,
    created_at          timestamptz not null default now()
);

-- ---------------------------------------------------------------------------------------
-- Transverse (§13.1, RG-11, §6.10)
-- ---------------------------------------------------------------------------------------

create table audit_log (
    id          bigint generated by default as identity primary key,
    actor_id    bigint references users (id),
    action      varchar(100) not null,
    object_type varchar(100) not null,
    object_id   varchar(100),
    result      varchar(20) not null,
    summary     text,
    trace_id    varchar(100),
    occurred_at timestamptz not null default now()
);

create table system_parameters (
    id          bigint generated by default as identity primary key,
    key         varchar(100) not null,
    value       text not null,
    description varchar(500),
    updated_at  timestamptz not null default now(),
    constraint uq_system_parameters_key unique (key)
);

-- ---------------------------------------------------------------------------------------
-- Index (§10.1 — statut, demandeur, équipe, catégorie, priorité et dates)
-- ---------------------------------------------------------------------------------------

create index idx_requests_status on requests (status);
create index idx_requests_requester on requests (requester_id);
create index idx_requests_request_type on requests (request_type_id);
create index idx_requests_priority on requests (priority);
create index idx_requests_submitted_at on requests (submitted_at);
create index idx_requests_current_step on requests (current_step_id);

create index idx_task_assignments_user on task_assignments (assigned_user_id);
create index idx_task_assignments_team on task_assignments (assigned_team_id);

create index idx_request_history_request on request_history (request_id);
create index idx_request_field_values_request on request_field_values (request_id);
create index idx_comments_request on comments (request_id);
create index idx_attachments_request on attachments (request_id);
create index idx_sla_events_request on sla_events (request_id);

create index idx_notifications_recipient on notifications (recipient_id, read_at);

create index idx_audit_log_occurred_at on audit_log (occurred_at);
create index idx_audit_log_object on audit_log (object_type, object_id);

create index idx_users_department on users (department_id);
create index idx_teams_department on teams (department_id);
