-- V5 : jeu de données de démonstration.
--
-- Ancrage : §17.1 ("jeu de données de démonstration" listé comme livrable) et REC-01/
-- REC-02 (un rôle donné doit pouvoir se connecter et constater son périmètre réel ; un
-- demandeur doit pouvoir sélectionner un service et compléter un formulaire existant).
-- Sans cette migration, aucun compte ne peut se connecter et AuthorizationService.canAct
-- n'a aucune donnée réelle à évaluer.
--
-- Portée délibérément limitée à la configuration et aux brouillons : organisation, rôles,
-- catalogue, formulaires, workflow, SLA. Deux demandes en statut DRAFT sont insérées pour
-- illustrer §6.3 ("conservation des valeurs saisies en brouillon") et RG-06, mais aucune
-- demande SOUMISE n'est fabriquée ici : produire une ligne request_history/sla_events
-- cohérente suppose le futur cas d'usage "exécuter une transition de workflow", qui
-- n'existe pas encore. Une demande soumise pré-insérée par SQL directement encoderait un
-- comportement métier non vérifié par ce code, ce que la migration ne doit pas faire.
--
-- Toutes les colonnes id sont "generated by default as identity" (V2) : cette migration
-- leur assigne des valeurs explicites basses pour que chaque insertion référence l'autre
-- par un identifiant lisible plutôt que par une sous-requête sur clé naturelle, puis
-- resynchronise chaque séquence d'identité sur le maximum inséré (bloc final) pour que la
-- prochaine ligne créée par l'application ne collisionne pas avec ces id fixes.
--
-- Mot de passe unique pour tous les comptes de démonstration : "Password123!"
-- (BCrypt, coût 10, généré par la même org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
-- que SecurityConfig.passwordEncoder() - §13 "hachage robuste").

-- ---------------------------------------------------------------------------------------
-- Organisation (§4.1) : une direction, deux services, une équipe par service
-- ---------------------------------------------------------------------------------------

insert into departments (id, name, parent_department_id, lead_id) values
    (1, 'Direction Générale', null, null),
    (2, 'Service Informatique', 1, null),
    (3, 'Service Achats', 1, null);

insert into users (id, first_name, last_name, email, password_hash, department_id, manager_id) values
    (1, 'Amina', 'Idrissi', 'amina.idrissi@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 2, null),
    (2, 'Leila', 'Chraibi', 'leila.chraibi@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 3, null),
    (3, 'Youssef', 'Amrani', 'youssef.amrani@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 2, null),
    (4, 'Sara', 'Bennis', 'sara.bennis@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 2, 3),
    (5, 'Karim', 'El Fassi', 'karim.elfassi@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 2, null),
    (6, 'Fatima', 'Squalli', 'fatima.squalli@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 3, null),
    (7, 'Reda', 'Bakkali', 'reda.bakkali@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 3, 6),
    (8, 'Nawal', 'Idrissi', 'nawal.idrissi@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 3, null),
    (9, 'Nadia', 'Ziani', 'nadia.ziani@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 1, null),
    (10, 'Omar', 'Tazi', 'omar.tazi@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 1, null),
    (11, 'Hicham', 'Alaoui', 'hicham.alaoui@smartflow.local', '$2a$10$lmJWexzyuuX2G0vrPfaR0u4GUaqnyj/LBsMV9ETJxGCJBh/WssoSq', 1, null);

-- amina.manager_id and youssef's chain are set after users exist, exactly like V2 breaks
-- the departments.lead_id <-> users circular dependency with a deferred alter/update.
update users set manager_id = 3 where id = 1;   -- Amina -> Youssef
update users set manager_id = 5 where id = 3;   -- Youssef -> Karim
update users set manager_id = 5 where id = 4;   -- Sara -> Karim
update users set manager_id = 6 where id = 2;   -- Leila -> Fatima
update users set manager_id = 8 where id = 6;   -- Fatima -> Nawal

update departments set lead_id = 5 where id = 2; -- Karim El Fassi (SERVICE_MANAGER)
update departments set lead_id = 8 where id = 3; -- Nawal Idrissi (SERVICE_MANAGER)

insert into teams (id, name, department_id, lead_id) values
    (1, 'Support Poste de travail', 2, 3),
    (2, 'Équipe Achats', 3, 6);

-- §5 - un rôle par compte suffit à illustrer chaque périmètre de ScopeRule ; rien
-- n'empêche un compte réel de cumuler plusieurs (user_role_assignments n'a pas de
-- contrainte d'unicité sur user_id seul, seulement sur la combinaison complète).
insert into user_role_assignments (id, user_id, role, scope_type, scope_id) values
    (1, 1, 'REQUESTER', 'OWN', null),
    (2, 2, 'REQUESTER', 'OWN', null),
    (3, 3, 'MANAGER', 'TEAM', 1),
    (4, 4, 'AGENT', 'TEAM', 1),
    (5, 5, 'SERVICE_MANAGER', 'DEPARTMENT', 2),
    (6, 6, 'MANAGER', 'TEAM', 2),
    (7, 7, 'AGENT', 'TEAM', 2),
    (8, 8, 'SERVICE_MANAGER', 'DEPARTMENT', 3),
    (9, 9, 'FUNCTIONAL_ADMIN', 'GLOBAL', null),
    (10, 10, 'TECHNICAL_ADMIN', 'GLOBAL', null),
    (11, 11, 'AUDITOR', 'GLOBAL', null);

-- ---------------------------------------------------------------------------------------
-- Catalogue de services (§6.2) : deux processus pilotes, un par service (§2.1)
-- ---------------------------------------------------------------------------------------

insert into service_catalog (id, name, description, category, department_id, display_order) values
    (1, 'Support Informatique', 'Matériel, accès applicatifs et assistance technique.', 'IT', 2, 1),
    (2, 'Achats et Approvisionnement', 'Demandes d''achat de matériel, licences et prestations.', 'Achats', 3, 1);

insert into request_types (id, service_catalog_id, name, description, target_delay_description, required_documents, contact_info, display_order) values
    (1, 1, 'Demande de matériel informatique', 'Poste de travail, périphérique ou accès à une application (§1.2).', 'Prise en charge sous 48h', 'Aucun document requis', 'support-it@smartflow.local', 1),
    (2, 2, 'Demande d''achat', 'Achat de matériel, licence ou prestation nécessitant une validation hiérarchique (§1.2).', 'Validation sous 5 jours ouvrés', 'Devis fournisseur', 'achats@smartflow.local', 1);

-- ---------------------------------------------------------------------------------------
-- Formulaires configurables (§6.3) : les huit types de champ, plus un affichage
-- conditionnel simple (urgency = 'Urgent' révèle urgent_justification)
-- ---------------------------------------------------------------------------------------

insert into form_definitions (id, request_type_id, version, status, published_at) values
    (1, 1, 1, 'PUBLISHED', now()),
    (2, 2, 1, 'PUBLISHED', now());

insert into form_fields (id, form_definition_id, code, label, field_type, required, display_order, help_text, visible_when_field_code, visible_when_value) values
    (1, 1, 'equipment_type', 'Type de matériel', 'TEXT', true, 1, 'Ex. ordinateur portable, écran, casque.', null, null),
    (2, 1, 'quantity', 'Quantité', 'NUMBER', true, 2, null, null, null),
    (3, 1, 'needed_by', 'Date souhaitée', 'DATE', false, 3, null, null, null),
    (4, 1, 'urgency', 'Niveau d''urgence', 'LIST', true, 4, null, null, null),
    (5, 1, 'has_manager_approval', 'Validation managériale déjà obtenue', 'CHECKBOX', false, 5, null, null, null),
    (6, 1, 'delegate', 'Utilisateur délégué pour le suivi', 'USER', false, 6, 'Optionnel : un collègue autorisé à suivre la demande.', null, null),
    (7, 1, 'target_department', 'Service destinataire du matériel', 'DEPARTMENT', false, 7, null, null, null),
    (8, 1, 'supporting_document', 'Pièce jointe justificative', 'FILE', false, 8, null, null, null),
    (9, 1, 'urgent_justification', 'Justification de l''urgence', 'TEXT', false, 9, 'Visible uniquement si le niveau d''urgence est "Urgent" (§6.3).', 'urgency', 'Urgent');

insert into field_options (id, form_field_id, value, label, display_order) values
    (1, 4, 'Faible', 'Faible', 1),
    (2, 4, 'Normal', 'Normal', 2),
    (3, 4, 'Urgent', 'Urgent', 3);

insert into form_fields (id, form_definition_id, code, label, field_type, required, display_order, help_text) values
    (10, 2, 'item_description', 'Description de l''achat', 'TEXT', true, 1, null),
    (11, 2, 'estimated_amount', 'Montant estimé (MAD)', 'NUMBER', true, 2, null),
    (12, 2, 'supplier_quote', 'Devis fournisseur', 'FILE', true, 3, 'Pièce obligatoire (voir "documents requis" du type de demande).'),
    (13, 2, 'priority_reason', 'Justification de priorité', 'LIST', false, 4, null);

insert into field_options (id, form_field_id, value, label, display_order) values
    (4, 13, 'Standard', 'Standard', 1),
    (5, 13, 'Prioritaire', 'Prioritaire', 2);

-- ---------------------------------------------------------------------------------------
-- Workflow (§6.5) : un circuit à 4 étapes pour le matériel informatique, avec une
-- condition simple sur la priorité (une demande CRITICAL saute la validation formelle),
-- un circuit à 4 étapes pour les achats - même moteur, deux configurations différentes
-- (§2.1 : pas de branche codée en dur par type de demande).
--
-- CLOSE n'a jamais d'étape cible (to_step_id null) : Transition.getToStep()'s propre
-- javadoc ("CLOSE is a terminal action with no target step") en fait un invariant du
-- moteur, pas une convention par workflow - l'exécuteur de transition s'appuie dessus pour
-- décider quand clore réellement la demande (statut CLOSED) plutôt que déplacer
-- currentStep. REJECT, lui, mène à une étape terminale bien réelle (REJETEE) : rien ne
-- l'empêche d'avoir une suite (§6.5 laisse cette étape configurable), seule son absence de
-- transitions sortantes en fait un cul-de-sac dans ce jeu de données.
-- ---------------------------------------------------------------------------------------

insert into workflow_definitions (id, request_type_id, version, status, published_at) values
    (1, 1, 1, 'PUBLISHED', now()),
    (2, 2, 1, 'PUBLISHED', now());

insert into steps (id, workflow_definition_id, code, name, display_order, responsible_role, responsible_team_id, suspend_sla) values
    (1, 1, 'QUALIFICATION', 'Qualification', 1, 'AGENT', 1, false),
    (2, 1, 'VALIDATION', 'Validation hiérarchique', 2, 'MANAGER', 1, false),
    (3, 1, 'TRAITEMENT', 'Traitement', 3, 'AGENT', 1, false),
    (4, 1, 'REJETEE', 'Rejetée', 4, null, null, false),
    (5, 2, 'QUALIFICATION', 'Qualification', 1, 'AGENT', 2, false),
    (6, 2, 'VALIDATION', 'Validation hiérarchique', 2, 'MANAGER', 2, false),
    (7, 2, 'TRAITEMENT', 'Traitement', 3, 'AGENT', 2, false),
    (8, 2, 'REJETEE', 'Rejetée', 4, null, null, false);

insert into transitions (id, from_step_id, action, to_step_id, condition_priority) values
    (1, 1, 'ASSIGN', 3, 'CRITICAL'),
    (2, 1, 'ASSIGN', 2, null),
    (3, 1, 'REQUEST_INFO', 1, null),
    (4, 2, 'VALIDATE', 3, null),
    (5, 2, 'REJECT', 4, null),
    (6, 2, 'RETURN', 1, null),
    (7, 3, 'CLOSE', null, null),
    (8, 3, 'REQUEST_INFO', 3, null),
    (9, 5, 'ASSIGN', 6, null),
    (10, 6, 'VALIDATE', 7, null),
    (11, 6, 'REJECT', 8, null),
    (12, 6, 'RETURN', 5, null),
    (13, 7, 'CLOSE', null, null);

-- ---------------------------------------------------------------------------------------
-- SLA (§6.7, RG-07) : un délai de prise en charge et de résolution par priorité et par
-- type de demande. use_business_calendar=false explicite (ADR-09 : hors socle).
-- ---------------------------------------------------------------------------------------

insert into sla (id, request_type_id, priority, first_response_minutes, resolution_minutes, use_business_calendar) values
    (1, 1, 'LOW', 480, 4320, false),
    (2, 1, 'MEDIUM', 240, 2880, false),
    (3, 1, 'HIGH', 60, 1440, false),
    (4, 1, 'CRITICAL', 30, 480, false),
    (5, 2, 'LOW', 1440, 10080, false),
    (6, 2, 'MEDIUM', 720, 7200, false),
    (7, 2, 'HIGH', 240, 4320, false),
    (8, 2, 'CRITICAL', 120, 1440, false);

-- Aucun system_parameters n'est semé pour security.separation-of-duties.enabled :
-- AuthorizationService y répond déjà "activé" en son absence (défaut sécurisé), et
-- AuthorizationServiceIT insère puis retire cette même ligne pour tester les deux
-- branches - un seed permanent sur cette clé entrerait en collision avec
-- uq_system_parameters_key dès le premier test de ce fichier.

-- ---------------------------------------------------------------------------------------
-- Brouillons de démonstration (§6.4, §6.3) : aucune soumission, donc pas d'étape
-- courante, pas d'historique, pas d'évènement SLA - voir l'en-tête de ce fichier.
-- Préfixées 900xxx pour ne jamais recouper les références numérotées bas que fabriquent
-- SlaSuspensionServiceIT (DEM-2026-000001) et AuthorizationServiceIT (DEM-2026-000010 et
-- suivantes) sur uq_requests_reference.
-- ---------------------------------------------------------------------------------------

insert into requests (id, reference, request_type_id, status, requester_id, title, description) values
    (1, 'DEM-2026-900001', 1, 'DRAFT', 1, 'Remplacement clavier et souris', 'Matériel actuel défectueux depuis deux semaines.'),
    (2, 'DEM-2026-900002', 2, 'DRAFT', 2, 'Achat de 3 licences logicielles', 'Licences nécessaires pour la nouvelle recrue du service.');

insert into request_field_values (id, request_id, form_field_id, value) values
    (1, 1, 1, 'Clavier et souris sans fil'),
    (2, 1, 2, '1'),
    (3, 1, 4, 'Normal'),
    (4, 2, 10, 'Suite bureautique - 3 postes'),
    (5, 2, 11, '4500');

-- ---------------------------------------------------------------------------------------
-- Resynchronisation des séquences d'identité (voir en-tête) : la prochaine ligne créée
-- par l'application via Hibernate doit repartir après le plus grand id inséré ci-dessus.
-- ---------------------------------------------------------------------------------------

select setval(pg_get_serial_sequence('departments', 'id'), (select max(id) from departments));
select setval(pg_get_serial_sequence('users', 'id'), (select max(id) from users));
select setval(pg_get_serial_sequence('teams', 'id'), (select max(id) from teams));
select setval(pg_get_serial_sequence('user_role_assignments', 'id'), (select max(id) from user_role_assignments));
select setval(pg_get_serial_sequence('service_catalog', 'id'), (select max(id) from service_catalog));
select setval(pg_get_serial_sequence('request_types', 'id'), (select max(id) from request_types));
select setval(pg_get_serial_sequence('form_definitions', 'id'), (select max(id) from form_definitions));
select setval(pg_get_serial_sequence('form_fields', 'id'), (select max(id) from form_fields));
select setval(pg_get_serial_sequence('field_options', 'id'), (select max(id) from field_options));
select setval(pg_get_serial_sequence('workflow_definitions', 'id'), (select max(id) from workflow_definitions));
select setval(pg_get_serial_sequence('steps', 'id'), (select max(id) from steps));
select setval(pg_get_serial_sequence('transitions', 'id'), (select max(id) from transitions));
select setval(pg_get_serial_sequence('sla', 'id'), (select max(id) from sla));
select setval(pg_get_serial_sequence('requests', 'id'), (select max(id) from requests));
select setval(pg_get_serial_sequence('request_field_values', 'id'), (select max(id) from request_field_values));

-- request_reference_seq (RG-01) n'est pas touché : les deux brouillons ci-dessus portent
-- une référence écrite à la main (voir le commentaire au-dessus de leur insertion), aucun
-- des deux ne consomme nextval('request_reference_seq'). La séquence reste à son point de
-- départ (V2 : start with 1), prête pour la première vraie soumission.
